# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wf_Client_Tests

on:
  push:
  pull_request:


env: 
  REACT_APP_GITHUB_OAUTH_CLIENT_ID: ${{secrets.REACT_APP_GITHUB_OAUTH_CLIENT_ID}}
  REACT_APP_GITHUB_REDIRECT_URI: ${{secrets.REACT_APP_GITHUB_REDIRECT_URI}}
  REACT_APP_GITHUB_STATE: ${{secrets.REACT_APP_GITHUB_STATE}}
  REACT_APP_API_BASE_URL: ${{secrets.REACT_APP_API_BASE_URL}}
  REACT_APP_FUNCTION_APP_KEY: ${{secrets.REACT_APP_TEST}}

jobs:
  job_Client_test_build_and_run:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: job_Client_Tests_${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: client/yarn.lock
    - run: printenv
    - run: env
    - run: cd client && yarn install --frozen-lockfile && npm run build --if-present && npm run test

